backend/forum/base/urls.py
from django.urls.conf import path

from .views.frontend import (
    TopicCommentListingView, TopicExpandCommentsDownView,
    TopicExpandCommentsUpView, TopicExpandRepliesUpRecursive, TopicListView)

urlpatterns_base = [
    path(route=r'', view=TopicListView.as_view(), name='topic-listing'),
    path(
        route='topic/<slug:topic_slug>/',
        view=TopicCommentListingView.as_view(), name='topic-comment-listing'),
    path(
        route='topic/<slug:topic_slug>/<int:comment_pk>/',
        view=TopicCommentListingView.as_view(), name='topic-comment-listing'),
    path(
        route='comments-up-recursive/<slug:topic_slug>/<int:comment_pk>'
        '/<int:scroll_to_pk>/', view=TopicExpandRepliesUpRecursive.as_view(),
        name='comments-up-recursive'),
    path(
        route=(
            'comments-up/<slug:topic_slug>/'
            '<int:comment_pk>/<int:scroll_to_pk>/'),
        view=TopicExpandCommentsUpView.as_view(), name='comments-up'),
    path(
        route=(
            'comments-down/<slug:topic_slug>/'
            '<int:comment_pk>/<int:scroll_to_pk>/'),
        view=TopicExpandCommentsDownView.as_view(), name='comments-down'),
]

backend/forum/rest_api/urls.py
from django.conf.urls import re_path
from django.urls.conf import path

from forum.base.views.api import (
    ArchivedTopicsStartView, TopicListPageView, UserSlugsView,
    v1_find_users_by_name)
from forum.cdn.views.imager_api import ResizeImageView

from .views.md_helper import md_parser

urlpatterns_api = [
    path(
        route='v1/user-short/<slug_list>/', view=UserSlugsView.as_view(),
        name='v1-user-short'),
    re_path(
        route=r'^v1/topic-list-page/', view=TopicListPageView.as_view(),
        name='v1-topic-list-page'),
    re_path(
        route=r'^v1/archived-topics-start/',
        view=ArchivedTopicsStartView.as_view(),
        name='v1-archived-topics-start'),
    re_path(
        route=r'v1/imager/resize/(?P<img_path>.*)$',
        view=ResizeImageView.as_view(), name='v1-imager-resize'),
    re_path(
        route=r'^v1/find-users-by-name/', view=v1_find_users_by_name,
        name='v1-find-users-by-name'),
    re_path(route=r'^v1/md-parser/', view=md_parser, name='md-parser'),
]

backend/forum/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.admin.sites import site
from django.urls.conf import include, path

from forum.account.urls import urlpatterns_account
from forum.base.urls import urlpatterns_base
from forum.rest_api.urls import urlpatterns_api

forum_urlpatterns = [
    url(regex=r'^api/', view=include(arg=(urlpatterns_api, 'rest-api'),
        namespace='rest-api')),
    url(regex=r'^account/', view=include(arg=(urlpatterns_account, 'account'),
        namespace='account')),
    url(regex=r'^', view=include(arg=(urlpatterns_base, 'base'),
        namespace='base')),
]

urlpatterns = [
    url(regex=r'^admin/', view=site.urls),
    url(regex=r'^', view=include(
        arg=(forum_urlpatterns, 'forum'), namespace='forum')),
]

if settings.DEBUG:
    # Add debug toolbar
    import debug_toolbar
    urlpatterns += [
        path(route='__debug__/', view=include(arg=debug_toolbar.urls))]
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

from base.choices import TOPIC_TYPE_CHOICES
from forum.utils import slugify


class Comment(models.Model):

    """
    Essential comment class.

    The hostname is obsoleted, but since there's no stable way to get
    IPs from hostnames, we store it. It was stored in the previous
    version like that.
    """

    class Meta:
        ordering = ('-time',)
        index_together = (
            ('topic', 'time'),
        )

    def __str__(self):
        return str(_('#%(number)s of \'%(topic)s\'' % {
            'number': self.number,
            'topic': self.topic
        }))

    user = models.ForeignKey(User, verbose_name=_('The commenter user'))
    topic = models.ForeignKey('Topic', verbose_name=_('Commented in topic'))
    moved_from = models.ForeignKey(
        'Topic', null=True, default=None, related_name='moved_from',
        verbose_name=_('Comment moved from topic'),
        on_delete=models.SET_DEFAULT)
    time = models.DateTimeField(
        # auto_now_add=True,
        verbose_name=_('Commented at'))
    number = models.PositiveIntegerField(
        verbose_name=_('Comment number in topic'))
    voting_value = models.SmallIntegerField(
        verbose_name=_('Value of up/downvotes'))
    prev_comment = models.ForeignKey(
        'self', related_name='reply_set', verbose_name=_('Replied comment'),
        null=True, default=None, on_delete=models.SET_DEFAULT)
    # FOR HTML ESCAPING IN MARKDOWN
    # https://pythonhosted.org/Markdown/release-2.6.html#safe_mode-deprecated
    content_md = models.TextField(verbose_name=_('Markdown content'))
    content_html = models.TextField(verbose_name=_('HTML content'))
    host = models.CharField(
        max_length=256, verbose_name=_('Host of the commenter (old)'))
    ip = models.GenericIPAddressField(
        verbose_name=_('IP of the commenter'), null=False, blank=False)
    unique_id = models.CharField(
        verbose_name=_('Obsolete unique ID'),
        default=0,
        max_length=20, unique=True)
    images = models.ManyToManyField(
        'cdn.Image', verbose_name=_('Images in this comment'))


class Edit(models.Model):

    """
    Comment edits.
    """

    comment = models.ForeignKey(
        'Comment', verbose_name=_('Edited comment'), null=False)
    edited_by = models.ForeignKey(
        User, verbose_name=_('Edited by'), null=False)
    timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name=_('Edit timestamp'), null=False)
    reason = models.CharField(
        verbose_name=_('Reason for editing'), max_length=50, null=False,
        default='')
    diff = models.TextField(
        verbose_name=_('Diff of the previous version'), null=False)
    images = models.ManyToManyField(
        'cdn.Image', verbose_name=_('Images in this edit'))


class Topic(models.Model):

    """
    Essential topic class.
    """

    class Meta(object):
        ordering = ['-last_comment__time', 'name_text']

    def __str__(self):
        return self.name_text

    creator = models.ForeignKey(User, verbose_name=_('Topic creator'))
    name_html = models.CharField(max_length=256, verbose_name=_('HTML name'))
    name_text = models.CharField(max_length=256, verbose_name=_('Text name'))
    is_enabled = models.BooleanField(
        default=False, verbose_name=_('Is topic enabled'))
    is_staff_only = models.BooleanField(
        default=False, verbose_name=_('Is staff only'))
    is_voting_enabled = models.BooleanField(
        default=True, verbose_name=_('Is voting enabled'))
    type = models.CharField(
        verbose_name=_('Topic type'), max_length=20,
        choices=TOPIC_TYPE_CHOICES, default=TOPIC_TYPE_CHOICES[0][0])
    truncate_at = models.SmallIntegerField(
        null=True, verbose_name=_('Max comment number to keep'))
    reply_to = models.ForeignKey(
        'self', null=True, default=None, on_delete=models.SET_NULL,
        verbose_name=_('Reply to topic goes to'))
    slug = AutoSlugField(
        verbose_name=_('Slug'), null=False, max_length=100,
        populate_from=('name_text',), unique=True, slugify_function=slugify)
    comment_count = models.PositiveIntegerField(
        verbose_name=_('Comment count'), default=0)
    last_comment = models.ForeignKey(
        Comment, verbose_name=_('Last comment reference'), null=True,
        related_name='last_comment', on_delete=models.SET_NULL)
    description = models.TextField(verbose_name=_('Description'))
    images = models.ManyToManyField(
        'cdn.Image', verbose_name=_('Images in this topic description'))


class Settings(models.Model):

    """
    An object representing the user's settings.
    """

    def _my_slugify(user_instance):
        """
        Returns the username from the OneToOneField relation to User.
        """
        return slugify(user_instance.username)

    def __str__(self):
        return str(self.user)

    user = models.OneToOneField(User, verbose_name=_('Respective user'))
    slug = AutoSlugField(
        verbose_name=_('Slug of the user'), max_length=50, unique=True,
        populate_from='user', slugify_function=_my_slugify, null=False)
    last_global_read = models.PositiveIntegerField(
        verbose_name=_('Last global message ID read'))
    received_comment_vote_sum = models.IntegerField(
        verbose_name=_('Summary received votes value on comments'))
    received_comment_vote_count = models.PositiveIntegerField(
        verbose_name=_('Summary received votes count on comments'))
    comment_vote_hide_limit = models.IntegerField(
        default=-5, verbose_name=_('Hide comments under this vote value'))
    quote = models.CharField(
        max_length=256, verbose_name=_('Chosen quote (appears at username)'))
    max_comments_per_day = models.PositiveIntegerField(
        verbose_name=_('Maximum allowed comments per day'))
    comment_count = models.PositiveIntegerField(
        verbose_name=_('Comment count'))
    invitations_today = models.PositiveIntegerField(
        verbose_name=_('Sent invitations today'))
    invited_by = models.ForeignKey(
        User, related_name='invited_user_setting_set', null=True,
        default=None, verbose_name=_('Invited by'))
    invitations_success = models.PositiveIntegerField(
        verbose_name=_('Successful invitations'))
    pw_reminders_today = models.PositiveIntegerField(
        verbose_name=_('Password reminders sent today'))
    used_skin = models.CharField(
        max_length=256, verbose_name=_('Used skin name'))
    introduction_md_all = models.TextField(
        verbose_name=_('Introduction visible for everybody (Markdown)'))
    introduction_md_reg = models.TextField(
        verbose_name=_('Introduction visible for registered users (Markdown)'))
    introduction_md_friends = models.TextField(
        verbose_name=_('Introduction visible for friended users (Markdown)'))
    introduction_html_all = models.TextField(
        verbose_name=_('Introduction visible for everybody (HTML)'))
    introduction_html_reg = models.TextField(
        verbose_name=_('Introduction visible for registered users (HTML)'))
    introduction_html_friends = models.TextField(
        verbose_name=_('Introduction visible for friended users (HTML)'))
    picture_emails = models.CharField(
        max_length=256, verbose_name=_(
            'Email addresses used for image upload'
            ' separated with semicolons (;)'))
    ignored_users = models.ManyToManyField(
        User, related_name='ignored_him',
        verbose_name=_('List of ignored users'))
    uses_auto_bookmarks = models.BooleanField(
        default=False, verbose_name=_('Use automatic bookmark placement'))
    mails_own_topic_comments = models.BooleanField(
        default=False, verbose_name=_(
            'Receive mails from comments in own topic'))
    mails_replies_topic = models.BooleanField(
        default=True, verbose_name=_('Receive mails from comment replies'))
    mails_moderation_topic = models.BooleanField(
        default=True, verbose_name=_('Receive mails from moderation'))
    mails_messages = models.BooleanField(
        default=True, verbose_name=_('Receive mails from messages'))
    show_replies_comment = models.BooleanField(
        default=True, verbose_name=_('Show replies on comments'))
    show_relations = models.BooleanField(
        default=True, verbose_name=_('Show user relations'))
    is_banned = models.BooleanField(
        default=False, verbose_name=_('User is banned'))
    separate_bookmarked_topics = models.BooleanField(
        default=True, verbose_name=_('Show bookmarked topics separated'))
    show_outsiders = models.BooleanField(
        default=True, verbose_name=_('Show not-logged-in users'))
    has_chat_enabled = models.BooleanField(
        default=True, verbose_name=_('Enable chat'))
    is_approved = models.BooleanField(
        default=False, verbose_name=_('Is approved by admins'))
    expand_archived = models.BooleanField(
        default=False, verbose_name=_('Expand archived topics'))
    friended_users = models.ManyToManyField(
        User, verbose_name=_('Friended users'), related_name='friended_him')
    images = models.ManyToManyField(
        'cdn.Image', verbose_name=_('Images in this user\'s descriptions'))


class CommentBookmark(models.Model):

    """
    A set bookmark for a comment object. A bookmark notes where the user
    left off reading comments the last time.
    """

    class Meta:
        verbose_name = _('Comment bookmark')
        verbose_name_plural = _('Comment bookmarks')
        unique_together = (('user', 'topic'),)

    def __str__(self):
        return str(_('s(number)s in %(topic)s for %(user)s') % {
            'number': self.comment.number,
            'topic': self.topic,
            'user': self.user
        })

backend/base/views.py
from django.shortcuts import render
from base.utils.home import collect_topics


def home(request):
    topics_highlighted, topics_normal = collect_topics(request)
    request_context = {
        'topics_highlighted': topics_highlighted,
        'topics_normal': topics_normal
    }
    return render(request, 'default/base/home.html', request_context)

backend/base/views/api.py
from decimal import Decimal

from base.utils.home import collect_topic_page
from django.core.paginator import InvalidPage
from django.db.models.aggregates import Avg, Count
from django.http.response import Http404, JsonResponse
from django.shortcuts import render
from rating.models import UserRating
from rest_api.exceptions import NotProduceable
from rest_api.utils import cast_to_set_of_slug

from ..choices import LIST_TOPIC_TYPE, TOPIC_TYPE_ARCHIVED
from ..models import Settings


def v1_user_short(request, slug_list):
    """
    Serve some short information about the requested user IDs such as
    quotes, and staff/superuser status and received ratings.
    """
    try:
        set_slug = cast_to_set_of_slug(slug_list)
    except NotProduceable as exc:
        return exc.json_response()
    qs_settings = Settings.objects.filter(
        slug__in=set_slug).select_related('user').only(
        'slug', 'quote', 'is_banned', 'user__is_staff', 'user__is_superuser')
    if qs_settings.count() != len(set_slug):
        raise Http404
    dict_result = {}
    dict_id_slug = {}
    for model_settings in qs_settings:
        dict_id_slug[model_settings.user_id] = model_settings.slug
        dict_result[model_settings.slug] = {
            'quote': model_settings.quote,
            'isSuperuser': model_settings.user.is_superuser,
            'isStaff': model_settings.user.is_staff,
            'isBanned': model_settings.is_banned,
            'rating': {
                # Default values here
                'avg': 0,
                'count': 0
            }
        }
    qs_ratings = UserRating.objects.filter(
        ratee_id__in=dict_id_slug.keys(), is_enabled=True).values(
        'ratee').annotate(Avg('value'), Count('value'))
    for rating in qs_ratings:
        user_id = rating['ratee']
        user_slug = dict_id_slug[user_id]
        rating_avg = round(Decimal(rating['value__avg']), 2)
        dict_result[user_slug]['rating']['avg'] = rating_avg
        dict_result[user_slug]['rating']['count'] = rating['value__count']
    return JsonResponse(dict_result)


def v1_topic_list_page(request):
    """
    Render a HTML for a topic page, requested by the paginating script.
    """
    # Sanitize input
    topic_type = request.GET.get('topic_type')
    if request.GET.get('topic_type') not in LIST_TOPIC_TYPE:
        raise Http404
    try:
        page_id = int(request.GET.get('page_id'))
    except (TypeError, ValueError):
        raise Http404
    try:
        topic_list = collect_topic_page(
            request=request, topic_type=topic_type, page_id=page_id,
            force=True)
    except InvalidPage:
        raise Http404
    return render(
        request=request,
        template_name='default/base/render-topic-group-page-inside.html',
        context={
            'topic_list': topic_list
        })


def v1_archived_topics_start(request):
    """
    Render the starter HTML for the archived topics, including the
    first page of the topic listing section, and the paginator wrapper.
    """
    qs_topics_archived = collect_topic_page(
        request=request, topic_type=TOPIC_TYPE_ARCHIVED, page_id=1, force=True)
    return render(
        request=request,
        template_name='default/base/topic-archived-start.html',
        context={
            'topic_list': qs_topics_archived
        })

backend/base/templates/default/base/home.html
{% extends 'default/base.html' %}
{% load i18n humanize %}
{% load render_bundle from webpack_loader %}

{% block extra_scripts_head %}
{% render_bundle 'topicGroup' %}
{% render_bundle 'userName' %}
<script type="text/javascript">
Forum.userName.init({
    urls: {
        shortData: '{% url 'rest-api:v1-user-short' slug_list='example-slug' %}',
        exampleSlug: 'example-slug'
    },
    selectors: {
        template: '.forum-user-tooltip-template'
    }
})
</script>
{% endblock extra_scripts_head %}

{% block main_content %}
    {% include 'default/include/user-tooltip-template.html' %}

    {% include 'default/base/include/topic-group.html' with topic_list=topics_highlighted topic_type='highlighted' %}

    {% include 'default/base/include/topic-group.html' with topic_list=topics_normal topic_type='normal' %}

    {% include 'default/base/include/topic-group.html' with topic_list=topics_archived topic_type='archived' %}
{% endblock main_content %}

backend/base/templates/default/base/topic-comment-listing.html
{% extends 'default/base.html' %}
{% load i18n humanize %}
{% load render_bundle from webpack_loader %}

{% block extra_scripts_head %}
{% render_bundle 'topicCommentListing' %}
{% endblock extra_scripts_head %}

{% block main_content %}
<article class="topic-comment-listing-wrapper">
    <template class="topic-comment-template">
    {% include 'default/base/include/topic-comment-template.html' with is_template=True %}
    </template>
    <template class="topic-comment-action-template">
    {% include 'default/base/include/topic-comment-action-template.html' %}
    </template>

    <section class="control-buttons text-center">
        <a href="{% url 'base:topic-listing' %}" class="btn btn-primary">
            <span class="fa fa-home" aria-hidden="true"></span>
            {% trans 'Back to topic listing' %}
        </a>
    </section>
    {% if model_topic.description %}
    <section class="card card-block card-outline-primary" aria-label="{% trans 'Topic description' %}">
        <div class="card-text">
            {{ model_topic.description|safe }}
        </div>
    </section>
    {% endif %}
    {% for model_comment in page_comments %}
        {% include 'default/base/include/topic-comment-template.html' with model_comment=model_comment %}
    {% endfor %}
</article>
<script type="text/javascript">
Forum.topicCommentListing.init({
    selectors: {
        root: '.topic-comment-listing-wrapper',
        template: {
            comment:'.topic-comment-template',
            action: '.topic-comment-action-template'
        },
        commentWrapper: '.topic-comment-wrapper',
        previousLinks: '.comment-previous a[data-link-to]',
        replyLinks: '.to-reply-comment',
        selfLinks: '.comment-number-wrapper .comment-number',
        commentActions: '.comment-actions',
        action: {
            voteUp: '.vote-up',
            voteDown: '.vote-down',
            expandCommentsDown: '.expand-comments-down',
            expandCommentsUp: '.expand-comments-up',
            replyToThis: '.reply-to-this'
        }
    },
    highlightedClass: 'is-highlighted',
    scrollTo: {{ comment_id|default:'null' }},
    topicSlug: '{{ topic_slug|escapejs }}',
    urls: {
        commentListing: {
            backend: '{% url 'base:topic-comment-listing' topic_slug='example-slug' comment_id=12345 %}',
            exampleSlug: 'example-slug',
            commentId: '12345'
        }
    }
})
</script>
{% endblock main_content %}

backend/base/templates/default/base/topic.html
{% extends 'default/base.html' %}
{% load i18n humanize %}
{% load render_bundle from webpack_loader %}

{% block extra_scripts_head %}
{% render_bundle 'topicCommentListing' %}
{% render_bundle 'userName' %}
<script type="text/javascript">
Forum.userName.init({
    urls: {
        shortData: '{% url 'rest-api:v1-user-short' slug_list='example-slug' %}',
        exampleSlug: 'example-slug'
    },
    selectors: {
        template: '.forum-user-tooltip-template'
    }
})
</script>
{% endblock extra_scripts_head %}

{% block main_content %}
    <article class="topic-comment-listing-wrapper">
    {% include 'default/include/user-tooltip-template.html' %}
    <template class="topic-comment-template">
    {% include 'default/base/include/topic-comment-template.html' %}
    </template>
    {% for model_comment in page_comments %}
        {% include 'default/base/include/topic-comment-template.html' with model_comment=model_comment %}
    {% endfor %}
    </article>
    <script type="text/javascript">
    Forum.topicCommentListing.init({
        selectors: {
            root: '.topic-comment-listing-wrapper',
            template: '.topic-comment-template',
            commentWrapper: '.topic-comment-wrapper',
            previousLinks: '.comment-previous a'
        },
        scrollTo: {{ comment_id|default:'null' }},
        topicSlug: '{{ topic_slug|escapejs }}',
        urls: {
            commentListing: {
                backend: '{% url 'topic' topic_slug='example-slug' comment_id=12345 %}',
                exampleSlug: 'example-slug',
                commentId: '12345'
            }
        }
    })
    </script>
{% endblock main_content %}